// tslint:disable
/**
 * FleetOnRoute API
 * <p>This API powers <a href='https://fleetonroute.com'>https://fleetonroute.com</a>.</p>    <p>To begin, authenticate using the <a href='#/auth/login'>Login</a> method below with your credentials. </p>    <p>To create an account, please log on to <a href='https://portal.fleetonroute.com'>https://portal.fleetonroute.com</a></p>    <p><a href=\"/public/oss-licenses.txt\">Open Source Attributions</a></p>
 *
 * OpenAPI spec version: 1.22.1
 * Contact: support@fleetonroute.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export * from "./api";
export * from "./configuration";
